In [1]:
from datasets import load_dataset
import pandas as pd
from tqdm import tqdm

LIMIT = 2_100_000

dataset = load_dataset(
    "ai4bharat/IndicCorpV2",
    split="hin_Deva",
    streaming=True
)

texts = []

for i, sample in enumerate(tqdm(dataset)):
    # Depending on dataset format
    if "text" in sample:
        texts.append(sample["text"])
    else:
        texts.append(list(sample.values())[0])

    if i + 1 == LIMIT:
        break

df = pd.DataFrame({"text": texts})

print(df.head())
print(len(df))

c:\Users\rajde\anaconda3\envs\pytrch310\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2099999it [03:01, 11579.50it/s]

                                                text
0      लोगों को बिलों संबंधी सुविधा देना ही उनका काम
1
2  इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...
3
4   जहां आई थी तबाही उस घाटी क्षेत्र में खतरा ज्यादा
2100000

In [2]:
df.drop_duplicates(subset=["text"], inplace=True)
df.dropna(subset=['text'], inplace=True)

updated_df = df[df['text'] != '']
updated_df.reset_index(drop=True, inplace=True)
updated_df

                                                      text
0            लोगों को बिलों संबंधी सुविधा देना ही उनका काम
1        इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...
2         जहां आई थी तबाही उस घाटी क्षेत्र में खतरा ज्यादा
3        इसके बाद केंद्र की ओर से प्रदेश सरकार को पीएमज...
4        यह पूछने पर कि इस बड़े मैच से पहले उनकी नींद ग...
...                                                    ...
1049339  प्राची देसाई की इमेज एक सीधी-सादी अभिनेत्री की...
1049340                   सथानीय स्तर पर सोने चांदी के भाव
1049341  दरअसल, सीएम शिवराज सिंह चौहान गुरुवार को मध्य ...
1049342  - चुनाव ड्यूटी में चली गए हैं जिले के आधे पुलि...
1049343  अंतर्राष्ट्रीय ओलंपिक समिति (आईओसी) की सदस्य न...

[1049344 rows x 1 columns]

In [3]:
updated_df.to_parquet(
    "hindi_texts_raw.parquet",
    engine="pyarrow",
    compression="snappy",
    index=False
)

In [4]:
import pandas as pd

df = pd.read_parquet('hindi_texts_raw.parquet')
df

                                                      text
0            लोगों को बिलों संबंधी सुविधा देना ही उनका काम
1        इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...
2         जहां आई थी तबाही उस घाटी क्षेत्र में खतरा ज्यादा
3        इसके बाद केंद्र की ओर से प्रदेश सरकार को पीएमज...
4        यह पूछने पर कि इस बड़े मैच से पहले उनकी नींद ग...
...                                                    ...
1049339  प्राची देसाई की इमेज एक सीधी-सादी अभिनेत्री की...
1049340                   सथानीय स्तर पर सोने चांदी के भाव
1049341  दरअसल, सीएम शिवराज सिंह चौहान गुरुवार को मध्य ...
1049342  - चुनाव ड्यूटी में चली गए हैं जिले के आधे पुलि...
1049343  अंतर्राष्ट्रीय ओलंपिक समिति (आईओसी) की सदस्य न...

[1049344 rows x 1 columns]

In [5]:
import re

In [20]:
def sentence_tokenizer(text):
  pattern = r'[^।!?॥]+[।!?॥]*'

  sentences = re.findall(pattern, text)
  return [
    sentence.strip() for sentence in sentences
  ]

In [21]:
sentence_tokenizer(df.iloc[1, 0])

['इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थी, जब पूर्व उपप्रधानमंत्री देवीलाल ने अपने पुत्र ओमप्रकाश चौटाला को अपना राजनीतिक उत्तराधिकारी घोषित किया था।',
 'हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के चलते पार्टी टूटने से बच गई थी।',
 '1989 में देवीलाल केन्द्र की राजनीति में सक्रिय हो गए थे और उनके उपप्रधानमंत्री बनने के पश्चात् उनके तीन बेटों जगदीश सिंह, रणजीत सिंह और ओमप्रकाश चौटाला में से रणजीत और ओमप्रकाश के बीच हरियाणा में उनकी राजनीतिक विरासत को लेकर जंग शुरू हो गई थी।',
 'उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेते हुए पार्टी की बागडोर ओमप्रकाश चौटाला के हवाले कर दी थी, जिसके बाद रणजीत की बगावत का असर पार्टी, संगठन और उनकी सरकार पर भी पड़ा था।',
 'उस समय रणजीत की नाराजगी के चलते उनके समर्थन में कई कैबिनेट मंत्रियों ने इस्तीफे दे दिए थे किन्तु तब पार्टी सुप्रीमो चौ. देवीलाल की हरियाणा की जनता पर इतनी मजबूत पकड़ थी कि ओमप्रकाश चौटाला को उत्तराधिकारी बनाने के उनके फैसले का जनता के बीच कोई खास विरोध नहीं हुआ था लेकिन आज स्थिति बिल्कुल विपरीत है।',
 'ओमप्रकाश चौटाला पिछले काफी समय से जेल में हैं और जेल में रहते पार्टी के साथ-साथ परिवार पर भी उनकी पकड़ काफी ढ़ीली हो गई है, इसी कारण उनमें अब देवीलाल जैसा वो सामर्थ्य नजर नहीं आता कि वे अपने फैसलों को बगैर किसी प्रतिरोध के लागू करा सकें।']

In [22]:
df['text'].shape

(1049344,)

In [23]:
tot_sentences = []
for txt in df.loc[:, 'text']:
  sentences = sentence_tokenizer(txt)
  tot_sentences.extend(sentences)

In [24]:
len(tot_sentences)

3035640

In [25]:
TOKEN_PATTERN = re.compile(
    r"""
    https?://\S+                     # URLs
    | www\.\S+
    | [A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}   # Email
    | \d{1,2}[/-]\d{1,2}[/-]\d{2,4}   # Dates
    | \d+\.\d+                       # Decimal
    | \d+                            # Integer
    | [.,!?;:"'(){}\[\]<>/\-—–।॥…%&@#$^*_+=|\\`~।]                # Punctuation
    | [\u0900-\u0963\u0966-\u097F]+               # Hindi words
    """,
    re.VERBOSE
)

In [26]:
def word_tokenizer(sentence):
  return re.findall(TOKEN_PATTERN, sentence)

In [29]:
word_tokenizer("यह एक rajdeeppa53@gmail.com वाक्य है। यह दूसरा 12/09/2025 वाक्य है।")

['यह',
 'एक',
 'rajdeeppa53@gmail.com',
 'वाक्य',
 'है',
 '।',
 'यह',
 'दूसरा',
 '12/09/2025',
 'वाक्य',
 'है',
 '।']

In [32]:
data_df = pd.DataFrame({"sentence": tot_sentences})
data_df.head()

                                            sentence
0      लोगों को बिलों संबंधी सुविधा देना ही उनका काम
1  इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...
2  हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...
3  1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...
4  उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...

In [34]:
data_df['words'] = data_df['sentence'].apply(word_tokenizer)
data_df['words_count'] = data_df['words'].apply(len)
data_df.head()

,sentence,words,words_count
0,लोगों को बिलों संबंधी सुविधा देना ही उनका काम,"[लोगों, को, बिलों, संबंधी, सुविधा, देना, ही, उ...",9
1,इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...,"[इनेलो, 1987, में, उस, वक्त, ऐसे, ही, दोराहे, ...",29
2,हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...,"[हालांकि, तब, पार्टी, पर, देवीलाल, की, मजबूत, ...",17
3,1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...,"[1989, में, देवीलाल, केन्द्र, की, राजनीति, में...",48
4,उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...,"[उन, परिस्थितियों, में, देवीलाल, ने, कड़ा, निर...",38

In [35]:
data_df.to_parquet(
  "hindi_texts_tokenized.parquet",
  engine="pyarrow",
  compression="snappy",
  index=False
)

In [36]:
df=pd.read_parquet(
  "hindi_texts_tokenized.parquet"
)

df.head()

,sentence,words,words_count
0,लोगों को बिलों संबंधी सुविधा देना ही उनका काम,"[लोगों, को, बिलों, संबंधी, सुविधा, देना, ही, उ...",9
1,इनेलो 1987 में उस वक्त ऐसे ही दोराहे पर खड़ी थ...,"[इनेलो, 1987, में, उस, वक्त, ऐसे, ही, दोराहे, ...",29
2,हालांकि तब पार्टी पर देवीलाल की मजबूत पकड़ के ...,"[हालांकि, तब, पार्टी, पर, देवीलाल, की, मजबूत, ...",17
3,1989 में देवीलाल केन्द्र की राजनीति में सक्रिय...,"[1989, में, देवीलाल, केन्द्र, की, राजनीति, में...",48
4,उन परिस्थितियों में देवीलाल ने कड़ा निर्णय लेत...,"[उन, परिस्थितियों, में, देवीलाल, ने, कड़ा, निर...",38

In [39]:
total_sentences=df.shape[0]
total_sentences

3035640

In [40]:
total_words=df['words_count'].sum()
total_words

66417699

In [44]:
total_characters = 0
for i in range(total_sentences):
  total_characters += len(df['sentence'][i])

total_characters

306490491

In [45]:
avg_sentence_length = total_words / total_sentences if total_sentences > 0 else 0
avg_sentence_length

21.879306834802545

In [46]:
avg_word_length = total_characters / total_words if total_words > 0 else 0
avg_word_length

4.61459062290008

In [47]:
all_tokens = []
df['words'].apply(lambda x: all_tokens.extend(x))
total_number_of_tokens = len(all_tokens)

all_unique_tokens = list(set(all_tokens))
total_number_of_unique_tokens = len(all_unique_tokens)
total_number_of_tokens, total_number_of_unique_tokens

(66417699, 546044)

In [49]:
TTR = total_number_of_unique_tokens / total_number_of_tokens if total_number_of_tokens > 0 else 0
TTR

0.008221362802707152

In [50]:
print(f"i.   Total number of sentences: {total_sentences:,}")
print(f"ii.  Total number of words: {total_words:,}")
print(f"iii. Total number of characters: {total_characters:,}")
print(f"iv.  Average Sentence Length: {avg_sentence_length:.2f} words/sentence")
print(f"v.   Average word length: {avg_word_length:.2f} characters/word")
print(f"vi.  Type/Token Ratio (TTR): {TTR:.6f} ({total_number_of_unique_tokens:,} unique / {total_number_of_tokens:,} total)")

i.   Total number of sentences: 3,035,640
ii.  Total number of words: 66,417,699
iii. Total number of characters: 306,490,491
iv.  Average Sentence Length: 21.88 words/sentence
v.   Average word length: 4.61 characters/word
vi.  Type/Token Ratio (TTR): 0.008221 (546,044 unique / 66,417,699 total)